/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prof;

import java.io.BufferedReader;
import java.io.FileReader;
import static prof.timetable.d;

/**
 *
 * @author Ankul
 */
public class ttDel extends javax.swing.JFrame {

    /**
     * Creates new form ttDel
     */String day;
        String sub;
        int time;
        timetable TimeTable ;
        printTT delPrint;
        MailMe mm ;
    public ttDel() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        TimeTable=new timetable();
        delPrint=new printTT();
        mm = new MailMe();
        delPrint.setVisible(false);
        //jButton2.setEnabled(false);
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(650, 450));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REMOVE SLOT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(209, 0, 102, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Subject Code:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(65, 65, 113, 46);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Start Time:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(65, 247, 113, 46);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(209, 229, 125, 46);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(209, 65, 125, 46);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 350, 190, 48);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Day Name:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(65, 160, 113, 46);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(209, 152, 125, 46);

        jButton2.setText("Submit!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(223, 304, 100, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon("H:\\SEM 4\\ITW\\PROF\\235493381-wallpaper-backgrounds-blue.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 510, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         for(int i=0;i<6; i++)
        {
            d[i]= new Day();
       
        }
         TimeTable.reset();
        int flag=1;
        day=jTextField3.getText();
        sub=jTextField2.getText();
        String txt=jTextField1.getText();
        time=Integer.parseInt(txt);
        if(day.equals("")||sub.equals("")||txt.equals(""))
        {
            jLabel4.setText("Enter above fields");
        }
        else
        {
             for (int i=0;i<6&&flag==1;i++)///searching day name and the call delete 
                {
                    //System.out.println("abc");
                    if((d[i].DayName).equals(day))
                    {
                        //System.out.println("abc");
                        TimeTable.deletep(sub,time,i);
                        flag=0;
                       }
                    
                }
             jLabel4.setText("Removed Successfully!");
             if(flag==0)
             {
                 String msg ="YOUR "+sub+" CLASS IS CANCELLED FROM "+time+"-"+(time+1)+" ON "+day+"\nHAPPY BIRTHDAY NILAY!\nPARTY KAHA H?\n-TEAM PROF";
                 String subj="CANCELLATION OF CLASS";
                 String[] arr = new String[2];
                 arr[0]=subj;
                 arr[1]=msg;
                 mm.main(arr);
             }
             delPrint.setVisible(true);
             TimeTable.print(d);
            // delPrint.jScrollPane2.setVisible(true);
          try
    { 
    //String filetext="",filecontent="";

    //File file=new File("C:\\Users\\Ankul\\Documents\\NetBeansProjects\\TrialFile\\final.txt");
    String filename="C:\\Users\\Ankul\\Documents\\NetBeansProjects\\prof\\ttPrint.txt";
    FileReader fr=new FileReader(filename);
    BufferedReader br=new BufferedReader(fr);
    StringBuilder sb=new StringBuilder();
    /*while(fr !=null)
    {
           filetext=br.readLine();
           sb.append(filetext);
           sb.append("\n");
    }*/
    //filecontent=sb.toString();
    //JOptionPane.showMessageDialog(null,"File is"+filecontent);
     delPrint.jTextArea2.read(br, null);
     br.close();
     delPrint.jTextArea2.requestFocus();
    // JScrollPane scrollPane =new JScrollPane( textArea );
    }
    catch(Exception ex){
    System.out.print("hi i am error");
    }
   }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ttDel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ttDel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ttDel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ttDel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ttDel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
